### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by SevenZhang123** [2654400439/NLP_UCAS_Task3#1]
您好师兄/师姐，看到您这个项目，应该是胡玥老师的NLP作业叭。我们最近也在上这个课，到了大作业阶段(关系抽取，事件抽取，机器翻译)，请问您那边还有当年的大作业备份嘛？若有，方便分享一下嘛？谢谢~

**Comment by 2654400439** [comment]
上传了~[https://github.com/2654400439/UCAS_NLP_FINAL_TASK](url)

**Comment by 2654400439** [comment]
上传了，在最新的仓库里，你看一下

**Comment by 2654400439** [comment]
https://github.com/2654400439/UCAS_NLP_FINAL_TASK
